language: go
sudo: false
before_script:
- go vet ./...
script: make release
deploy:
  provider: releases
  api_key:
    secure: JVtbHWg6bnEUNA16J7bWPtLuHlWzJrN9UtLk5SttuP41Mv9H+a5g5b874aGLGHL3xuWNgyiTeb1OsKQALhkIEj2TbC0TQH082bF7/xacYYTzLt2DDjZz2hJ9uqEX+O5LHMfuLyaHGqIHa4RtaUNnhlp09IDKFmLJevcVppigygF7baLEvQKmedpysUm5bbao6hZXME+KYjiOafvLz7xYmbqxpbeNMTgvwJgqpN03xCklSPu+m/CKNc7bx3sXiKo67CX1ZtZTRKiccaQmb+GueA3dqxNGKwThlVhH0JSMeL/DnqI7izwZ+lskJbBi1am21HfmMaYZYmP4CgtxYcGYqbHa2kQUcAQv7OxOQQNeXuEWIUfY2duTOMq46RzYs68wO4IAxMYX5dUxEK4pi4n5d9Q6LHUUk6XudDjBBmv9HYFurrihbWcyNO1e1LAtTtxycs9B2LFDm+eLSOxVDJozNqqHGSNOS/QM+yNGGhZP3k65ZTmcKiaevVgl+kUP+E0UIlM4xOQqegUMLk6olTj1iJO2JcEbIV0oO0IKkoo3wdVm5euN2zHmbf2OQzO+r1PmqtjlJFZ8aGY1tEUsC1Wwbz4u3N+Il/N54yj7gqmoHiOSZnzxlnYGssycAhpDAFVY2GpHdY4UoIJ8A3+i1nFWEJoSHlcZWgQVc0kZ29XM910=
  file:
  - iocee_linux_amd64.bin
  - iocee_windows_amd64.exe
  on:
    repo: DCSO/iocee
    tags: true
